database:
  type: "SQLite"
  host: "127.0.0.1"
  port: "3306"
  database_name: "db_name"
  table-name: "ez_whitelist"
  user: "root"
  pass: "Admin@123"

legacy-colors: false

# DO NOT TOUCH!
config-version: 1

